= Set up Redis workers
Although the Redis master is a single pod, you can make it highly available and meet traffic demands by adding a few Redis worker replicas.

== Deploy Redis slaves

`kubernetes-istio-workshop/guestbook/redis-slave-service.yaml` manifest define two replicas for the Redis workers. Use the following command to start the two replicas on your container cluster.
```shell
kubectl apply -f guestbook/redis-slave-deployment.yaml
```

Verify that the two Redis worker replicas are running by querying the list of Pods.
```shell
kubectl get pods
```

== Create redis-slave service
The guestbook application needs to communicate to Redis workers to read data. To make the Redis workers discoverable, you need to set up a Service. A Service provides transparent load balancing to a set of Pods.

`guestbook/redis-slave-service.yaml` defines a Service named redis-slave running on port 6379. Note that the selector field of the Service matches the Redis worker Pods created in the previous step.

```shell
kubectl apply -f guestbook/redis-slave-service.yaml
```
Verify that the Service is created:
```shell
kubectl get service
```

