= Deploy Microservices
include::_attributes.adoc[]

[#deploycustomer]
== Deploy customer

Make sure you are logged in

[source,bash]
----
kubectl config current-context
----

and you have setup the project/namespace

[source,bash]
----
kubectl create namespace tutorial
kubectl config set-context $(kubectl config current-context) --namespace=tutorial
----

Then clone the git repository

[source,bash]
----
git clone https://github.com/sfeir/kubernetes-istio-workshop
cd istio-tutorial
----

Start deploying the microservice projects, starting with customer

=== Deploy Customer

Now let's deploy the customer pod with its sidecar

[source,bash]
----
kubectl apply -f manifests/kubernetes/customer.yml
----

=== Expose customer

Since the `customer` service is the one our users will interact with, you need to make it accessible from outside of your Kubernetes cluster. An Istio https://istio.io/docs/concepts/traffic-management/#gateways[Gateway] is used for this purpose.


[source,bash]
----
kubectl apply -f manifests/istio/gateway/customer-gateway.yml
----

Wait until the status is `Running` and there are `2/2` pods in the `Ready` column. To exit, press `Ctrl+C`

Then test the customer endpoint

[source,bash]
----
curl $CUSTOMER_URL
----

You should see the following error because the services `preference` and `recommendation` are not yet deployed.

----
customer => I/O error on GET request for "http://preference:8080": preference; nested exception is java.net.UnknownHostException: preference
----

Also review the logs

[source,bash]
----
stern customer -c customer
----

You should see a stacktrace containing this cause:

[source,bash]
----
org.springframework.web.client.ResourceAccessException: I/O error on GET request for "http://preference:8080": preference; nested exception is java.net.UnknownHostException: preference
----

[#deploypreference]
== Deploy preference

=== Preference build using Docker daemon

[source,bash]
----
kubectl apply -f manifests/kubernetes/preference-v1.yml
----

=== Wait preference to be deployed

[source, bash]
----
kubectl get pods -w
----

Wait until the status is `Running` and there are `2/2` pods in the `Ready` column. To exit, press `Ctrl+C`

[source,bash]
----
curl $CUSTOMER_URL
----

It will respond with an error since the service `recommendation` is not yet deployed.

NOTE: We could make this a bit more resilient in a future iteration of this tutorial

[source,bash]
----
customer => 503 preference => I/O error on GET request for "http://recommendation:8080": recommendation; nested exception is java.net.UnknownHostException: recommendation
----

and check out the logs

[source,bash]
----
stern preference -c preference
----

You should see a stacktrace containing this cause:

[source,bash]
----
org.springframework.web.client.ResourceAccessException: I/O error on GET request for "http://recommendation:8080": recommendation; nested exception is java.net.UnknownHostException: recommendation
----

[#deployrecommendation]
== Deploy recommendation

IMPORTANT: The tag `v1` at the end of the image name matters. We will be creating a `v2` version of `recommendation` later in this tutorial. Having both a `v1` and `v2` version of the `recommendation` code will allow us to exercise some interesting aspects of Istio's capabilities.


[source,bash]
----
kubectl apply -f manifests/kubernetes/recommendation-v1.yml
----

=== Wait recommendation to be deployed

Wait until the status is `Running` and there are `2/2` pods in the `Ready` column. To exit, press `Ctrl+C`

[source,bash]
----
curl $CUSTOMER_URL
----

it should now return

[source,bash]
----
customer => preference => recommendation v1 from '99634814-sf4cl': 1
----

and you can monitor the `recommendation` logs with

[source,bash]
----
stern recommendation -c recommendation
----
