= Deploy Microservices
include::_attributes.adoc[]

[#create-namespace]
== Create Namespace

Create a namespace called ``tutorial`` and enable Istio sidecar injection.

[source,bash]
----
kubectl create namespace tutorial
kubectl label namespace tutorial istio-injection=enabled
kubectl config set-context $(kubectl config current-context) --namespace=tutorial
----

Make sure yout are in the ``kubernetes-istio-workshop`` directory.

Start deploying the microservice projects, starting with customer

[#deploycustomer]
=== Deploy Customer

Now let's deploy the customer pod with its sidecar

[source,bash]
----
kubectl apply -f manifests/kubernetes/customer.yml
----

=== Expose customer

Since the `customer` service is the one our users will interact with, you need to make it accessible from outside of your Kubernetes cluster. An Istio https://istio.io/docs/concepts/traffic-management/#gateways[Gateway] is used for this purpose.


1. Define the ingress gateway for the application:
[source,bash]
----
kubectl apply -f manifests/istio/gateway/customer-gateway.yml
----

In the following definition, every hit to ``/`` (``prefix : /``) will be routed to the service customer (``host: customer``).
[source,yaml]
----
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: customer-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: customer-gateway
spec:
  hosts:
  - "*"
  gateways:
  - customer-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: customer
        port:
          number: 8080

----

2. Confirm the gateway has been created:

[source,bash]
----
kubectl get gateway
----

3. set the ``INGRESS_HOST`` and ``INGRESS_PORT`` variables for accessing the gateway :

Execute the following command to make sure that the External-IP of the gateway is not in <pending> state.

Set the ingress IP and ports:

[source,bash]
----
export INGRESS_HOST=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
export INGRESS_PORT=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.spec.ports[?(@.name=="http2")].port}')
export SECURE_INGRESS_PORT=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.spec.ports[?(@.name=="https")].port}')
----

4. Set GATEWAY_URL:

export GATEWAY_URL=$INGRESS_HOST:$INGRESS_PORT

5. Proceed to Confirm the app is running, below.

$ curl -o /dev/null -s -w "%{http_code}\n" http://${GATEWAY_URL}/

6. Then test the customer endpoint. Because of the route defined in the VirtualService, the URL of the customer service is the same as the URL of the gateway.

[source,bash]
----
export CUSTOMER_URL=$GATEWAY_URL

curl $CUSTOMER_URL
----

You should see the following error because the services `preference` and `recommendation` are not yet deployed.

[source,bash]
----
customer => I/O error on GET request for "http://preference:8080": preference; nested exception is java.net.UnknownHostException: preference
----

Also review the logs

[source,bash]
----
kubectl logs -l app=customer -c customer
----

You should see a stacktrace containing this cause:

[source,bash]
----
org.springframework.web.client.ResourceAccessException: I/O error on GET request for "http://preference:8080": preference; nested exception is java.net.UnknownHostException: preference
----

[#deploypreference]
== Deploy preference

=== Preference build using Docker daemon

[source,bash]
----
kubectl apply -f manifests/kubernetes/preference-v1.yml
----

=== Wait preference to be deployed

[source, bash]
----
kubectl get pods -w
----

Wait until the status is `Running` and there are `2/2` pods in the `Ready` column. To exit, press `Ctrl+C`

[source,bash]
----
curl $CUSTOMER_URL
----

It will respond with an error since the service `recommendation` is not yet deployed.

NOTE: We could make this a bit more resilient in a future iteration of this tutorial

[source,bash]
----
customer => 503 preference => I/O error on GET request for "http://recommendation:8080": recommendation; nested exception is java.net.UnknownHostException: recommendation
----

and check out the logs

[source,bash]
----
kubectl logs -l app=preference -c preference
----

You should see a stacktrace containing this cause:

[source,bash]
----
org.springframework.web.client.ResourceAccessException: I/O error on GET request for "http://recommendation:8080": recommendation; nested exception is java.net.UnknownHostException: recommendation
----

[#deployrecommendation]
== Deploy recommendation

IMPORTANT: The tag `v1` at the end of the image name matters. We will be using a `v2` version of `recommendation` later in this tutorial. Having both a `v1` and `v2` version of the `recommendation` code will allow us to exercise some interesting aspects of Istio's capabilities.


[source,bash]
----
kubectl apply -f manifests/kubernetes/recommendation-v1.yml
----

=== Wait recommendation to be deployed

Wait until the status is `Running` and there are `2/2` pods in the `Ready` column. To exit, press `Ctrl+C`

[source,bash]
----
curl $CUSTOMER_URL
----

it should now return

[source,bash]
----
customer => preference => recommendation v1 from '99634814-sf4cl': 1
----

and you can monitor the `recommendation` logs with

[source,bash]
----
kubectl logs -l app=recommendation -c recommendation
----
