= Egress
include::_attributes.adoc[]

Let's see an example of using egress route by deploying a recommendation:v3 version. Egress service entry allow you to apply rules to how internal services interact with external services.

In this case, we are going to configure Istio to access http://now.httpbin.org from internal service (recommendation:v3).

[#createrecommendationv3]
== Create recommendation:v3

We can experiment with Egress service entry by making two changes to `RecommendationVerticle.java` like the following and creating a "v3" docker image.

First change is updating the response string to:

[source,java]
----
private static final String RESPONSE_STRING_FORMAT = "recommendation v3 from '%s': %d\n";
----

The second change is to change the default output to make a call to http://now.httpbin.org.

From:

[source, java]
----
        router.get("/").handler(this::getRecommendations);
//        router.get("/").handler(this::getNow);
----

To:

[source, java]
----
//        router.get("/").handler(this::getRecommendations);
        router.get("/").handler(this::getNow);
----

_Important:_ We have a 3rd Deployment to manage the v3 version of recommendation.

[source,bash]
----
kubectl apply -f manifests/kubernetes/recommendation-v3.yml
----

=== Wait for v3 to be deployed

Wait for those pods to show "2/2", the istio-proxy/envoy sidecar is part of that pod

[source,bash]
----
NAME                                  READY     STATUS    RESTARTS   AGE
customer-3600192384-fpljb             2/2       Running   0          17m
preference-243057078-8c5hz            2/2       Running   0          15m
recommendation-v1-60483540-9snd9      2/2       Running   0          12m
recommendation-v2-2815683430-vpx4p    2/2       Running   0          15s
recommendation-v3-7b445dd469-j6rkg    2/2       Running   0          2m
----

[#istioegress]
== Istio-ize Egress

Be sure you do not have any previous destination rule nor virtual service installed.

Let's redirect all traffic to reccomendation:v3.

[source, bash]
----
kubectl apply -f manifests/istio/egress/recommendation-destination-rule-v1-v2-v3.yml
kubectl apply -f manifests/istio/egress/recommendation-v3-virtual-service.yml
----

Then access to the service:

IMPORTANT: Since no Egress service entry has been registered to access an external site, the timeout error is thrown after 5 seconds of trying to access to the site.
.
[source, bash]
----
$ curl -m 5 $CUSTOMER_URL
curl: (28) Operation timed out after 5000 milliseconds with 0 bytes received
----

Let's fix it by registering a service entry to allow access to `httpbin`.

[source,bash]
----
kubectl apply -f manifests/istio/egress/httpbin-service-entry-egress.yml
kubectl get serviceentry
curl $CUSTOMER_URL
customer => preference => Mon, 16 Jul 2018 12:03:38 GMT recommendation v3 from '7b445dd469-j6rkg': 1
----

or shell into the pod by getting its name and then using that name with oc exec

[source,bash]
----
kubectl exec -it $(kubectl get pods -o jsonpath="{.items[*].metadata.name}" -l app=recommendation,version=v3) -c recommendation -- curl http://now.httpbin.org
----

=== Clean up

[source,bash]
----
kubectl delete ServiceEntry httpbin-egress-rule
kubectl delete DestinationRule recommendation
kubectl delete VirtualService recommendation
----
